name = "PowerDynamicsCGMES"
uuid = "1b881f36-751d-4bf3-93fd-6a61c3d2f0d2"
authors = ["Hans Würfel <git@wuerfel.io> and contributors"]
version = "1.0.0-DEV"

[deps]
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PowerDynamics = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
OrderedCollections = "1.8.1"
XML = "0.3.6"
julia = "1.10"
